[package]
name = "brainfuck_prover"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true

[lints]
workspace = true

[dependencies]
brainfuck_vm.workspace = true
stwo-prover.workspace = true
num-traits.workspace = true
brainfuck_vm.workspace = true
