[package]
name = "brainfuck_prover"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true

[lints]
workspace = true

[dependencies]
stwo-prover.workspace = true
