pub mod end_of_execution;
pub mod input_component;
pub mod jump;
pub mod left_component;
pub mod minus_component;
pub mod output_component;
pub mod plus_component;
pub mod right_component;
pub mod table;
