name: CI

on:
  pull_request:
    branches:
      - "*"

permissions:
  deployments: read
  contents: read
  pull-requests: write

jobs:
  machete:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2024-01-04
      - uses: Swatinem/rust-cache@v2
      - run: cargo install --locked cargo-machete
      - run: cargo machete

  run-brainfuck-vm-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2024-01-04
      - uses: Swatinem/rust-cache@v2
      - run: cargo test --test '*' --lib

  run-brainfuck-vm-integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2024-01-04
      - uses: Swatinem/rust-cache@v2
      - run: cargo test --test '*'

  all-tests:
    runs-on: ubuntu-latest
    needs:
      - machete
      - run-brainfuck-vm-unit-tests
      - run-brainfuck-vm-integration-tests

    steps:
      - uses: re-actors/alls-green@v1.2.2
        with:
          jobs: ${{ toJSON(needs) }}
